version: '3.9'

services:

  app:
    build: ./app
    container_name: front-end 
    volumes: ['./app/src:/appcode', './secrets:/secrets']
      #    restart: unless-stopped
    ports:
      - 8501:8501

  api:
    build: ./api
    container_name: web-api
    volumes: ['./api:/apicode']
      
    ports:
      - 4000:4000

  db:
    image: mysql:8
    container_name: mysql_db
    volumes:
      - ./database:/docker-entrypoint-initdb.d/:ro

    ports:
      - 3200:3306

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/secret_db_root_pw
      MYSQL_USER: webapp
      MYSQL_PASSWORD_FILE: /run/secrets/secret_db_pw

    secrets:
        - secret_db_pw
        - secret_db_root_pw

secrets:
  secret_db_pw:
    file: ./secrets/db_password.txt
  secret_db_root_pw:
    file: ./secrets/db_root_password.txt
